name: 📈 Auto Update LeetCode Stats & Dev Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: MuhammadTahaNasir
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: LeetCode
          plugin_languages_sections: most-used
          plugin_languages_limit: 6

          plugin_leetcode: yes
          plugin_leetcode_user: muhamamadtahanasir
